export const DATA_TEST_ID = {
    footer: 'footer',
    header: 'header',
    juiciestLink: 'juiciest-link',
    juiciestLinkMobile: 'juiciest-link-mobile',
    veganCuisine: 'vegan-cuisine',
    BREADCRUMBS: 'breadcrumbs',
    CAROUSEL: 'carousel',
    HUMB_ICON: 'hamburger-icon',
    CLOSE_ICON: 'close-icon',
    SEARCH_INPUT: 'search-input',
    SEARCH_BUTTON: 'search-button',
    FOOD_CARD: 'food-card',
    CAROUSEL_CARD: 'carousel-card',
    ALLERGEN_SWITCHER: 'allergens-switcher',
    ALLERGEN_BUTTON: 'allergens-menu-button',
    FILTER_DRAWER: 'filter-drawer',
    FILTER_BUTTON: 'filter-button',
    FIND_RECIPE_BUTTON: 'find-recipe-button',
    FILTER_CATEGORY: 'filter-menu-button-категория',
    VEGAN_CHECKBOX: 'checkbox-веганская кухня',
    ALLERGEN_SWITCHER_FILTER: 'allergens-switcher-filter',
    ALLERGEN_BUTTON_FILTER: 'allergens-menu-button-filter',
    ADD_OTHER_ALLERGEN: 'add-other-allergen',
    ADD_ALLERGEN_BUTTON: 'add-allergen-button',
    FILTER_TAG: 'filter-tag',
    APP_LOADER: 'app-loader',
    ERROR_NOTIFICATION: 'error-notification',
    CLOSE_ALERT: 'close-alert-button',
    LOAD_MORE_BTN: 'load-more-button',
    LOADER_SEARCH: 'loader-search-block',
    ERROR_PAGE: 'error-page-go-home',
};
