export { default as ButtonModal} from './Button'
export { default as IconExit} from './Icon-exit'
export { default as Loader} from './Loader'
export { default as RateComponent} from './Rate'
export { default as Tabs} from './Tabs'